import { ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, SelectQueryBuilder } from 'typeorm';
import { ActivityLog, ProjectMember, Task, TaskApproval } from '../entities';
import { Role } from '../common/enums/role.enum';
import { TaskStatus } from '../common/enums/task.enum';
import { ProjectsService } from '../projects/projects.service';
import { TemporalService } from '../temporal/temporal.service';
@Injectable()
export class TasksService {
  constructor(@InjectRepository(Task) private readonly tasks: Repository<Task>, @InjectRepository(TaskApproval) private readonly approvals: Repository<TaskApproval>, @InjectRepository(ActivityLog) private readonly logs: Repository<ActivityLog>, @InjectRepository(ProjectMember) private readonly members: Repository<ProjectMember>, private readonly projects: ProjectsService, private readonly temporal: TemporalService) {}
  async create(dto: any, user: any) { await this.projects.assertMember(dto.projectId, user); const t = await this.tasks.save(this.tasks.create({ ...dto, status: dto.status ?? TaskStatus.TODO })); await this.logs.save(this.logs.create({ taskId: t.id, userId: user.id, action: 'task.created' })); if (t.dueDate) { const id = await this.temporal.startDeadline(t.id, t.dueDate); t.escalationWorkflowId = id; await this.tasks.save(t); } return t; }
  async list(q: any, user: any) { const qb = this.tasks.createQueryBuilder('task').where('1=1'); if (user.role !== Role.ADMIN) qb.andWhere('task.project_id IN (SELECT project_id FROM project_members WHERE user_id = :uid)', { uid: user.id }); if (q.status) qb.andWhere('task.status = :status', { status: q.status }); if (q.priority) qb.andWhere('task.priority = :priority', { priority: q.priority }); if (q.projectId) qb.andWhere('task.project_id = :projectId', { projectId: q.projectId }); if (q.assigneeId) qb.andWhere('task.assignee_id = :assigneeId', { assigneeId: q.assigneeId }); if (q.dueBefore) qb.andWhere('task.due_date <= :dueBefore', { dueBefore: q.dueBefore }); if (q.dueAfter) qb.andWhere('task.due_date >= :dueAfter', { dueAfter: q.dueAfter }); if (q.search) qb.andWhere(`to_tsvector('english', coalesce(task.title,'') || ' ' || coalesce(task.description,'')) @@ websearch_to_tsquery('english', :search)`, { search: q.search }); const sort = ({ createdAt: 'task.created_at', dueDate: 'task.due_date', priority: 'task.priority' } as any)[q.sortBy ?? 'createdAt']; qb.orderBy(sort, q.order ?? 'DESC').skip(((q.page ?? 1) - 1) * (q.limit ?? 20)).take(q.limit ?? 20); const [data, total] = await qb.getManyAndCount(); return { data, meta: { total, page: q.page ?? 1, limit: q.limit ?? 20 } }; }
  async get(id: string, user: any) { const t = await this.tasks.findOne({ where: { id } }); if (!t) throw new NotFoundException('Task not found'); await this.projects.assertMember(t.projectId, user); const [approvals, activity] = await Promise.all([this.approvals.find({ where: { taskId: id }, order: { stepOrder: 'ASC' } }), this.logs.find({ where: { taskId: id }, order: { createdAt: 'ASC' } })]); return { ...t, approvals, activity }; }
  async update(id: string, dto: any, user: any) { const t = await this.tasks.findOne({ where: { id } }); if (!t) throw new NotFoundException('Task not found'); await this.projects.assertMember(t.projectId, user); if (user.role !== Role.ADMIN && t.assigneeId !== user.id && user.id !== (await this.projects.get(t.projectId, user)).ownerId) throw new ForbiddenException('Task ownership required'); const before = { ...t }; Object.assign(t, dto); const saved = await this.tasks.save(t); for (const key of Object.keys(dto)) if ((before as any)[key] !== (dto as any)[key]) await this.logs.save(this.logs.create({ taskId: id, userId: user.id, action: `task.${key}_changed`, oldValue: String((before as any)[key] ?? ''), newValue: String((dto as any)[key] ?? '') })); if (saved.status === TaskStatus.DONE && saved.escalationWorkflowId) await this.temporal.cancelDeadline(saved.escalationWorkflowId); return saved; }
  async remove(id: string, user: any) { const t = await this.tasks.findOne({ where: { id } }); if (!t) throw new NotFoundException('Task not found'); await this.projects.assertMember(t.projectId, user); await this.tasks.softRemove(t); }
  async assign(id: string, assigneeId: string | null, user: any) { return this.update(id, { assigneeId }, user); }
  async submitApproval(id: string, approverIds: string[], user: any) { const t = await this.tasks.findOne({ where: { id } }); if (!t) throw new NotFoundException('Task not found'); await this.projects.assertMember(t.projectId, user); await this.approvals.save(approverIds.map((approverId, stepOrder) => this.approvals.create({ taskId: id, approverId, stepOrder }))); const workflowId = await this.temporal.startApproval(t.id, approverIds); t.approvalWorkflowId = workflowId; t.status = TaskStatus.IN_REVIEW; await this.tasks.save(t); return { workflowId }; }
  async approvalDecision(id: string, approvalId: string, decision: string, comment?: string) { const approval = await this.approvals.findOne({ where: { id, taskId: id } }); if (!approval) throw new NotFoundException('Approval not found'); approval.status = decision; approval.comment = comment ?? null; approval.decidedAt = new Date(); await this.approvals.save(approval); const task = await this.tasks.findOne({ where: { id } }); if (task?.approvalWorkflowId) await this.temporal.signalApproval(task.approvalWorkflowId, decision, comment); return approval; }
}
