import { ForbiddenException, Injectable, NotFoundException, BadRequestException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { ActivityLog, ProjectMember, Task, TaskApproval } from '../entities';
import { ApprovalStatus, TaskStatus } from '../common/enums/task.enum';
import { Role } from '../common/enums/role.enum';
import { ProjectsService } from '../projects/projects.service';
import { TemporalService } from '../temporal/temporal.service';
import { UsersService } from '../users/users.service';

@Injectable()
export class TasksService {
  constructor(@InjectRepository(Task) private readonly tasks: Repository<Task>, @InjectRepository(TaskApproval) private readonly approvals: Repository<TaskApproval>, @InjectRepository(ActivityLog) private readonly logs: Repository<ActivityLog>, @InjectRepository(ProjectMember) private readonly members: Repository<ProjectMember>, private readonly projects: ProjectsService, private readonly temporal: TemporalService, private readonly users: UsersService) {}
  async create(dto: any, user: any) { await this.projects.assertMember(dto.projectId, user); if (dto.assigneeId) await this.assertProjectMember(dto.projectId, dto.assigneeId); const task = await this.tasks.save(this.tasks.create({ ...dto, status: dto.status ?? TaskStatus.TODO })); await this.logs.save(this.logs.create({ taskId: task.id, userId: user.id, action: 'task.created' })); if (task.dueDate) { task.escalationWorkflowId = await this.temporal.startDeadline(task.id, task.dueDate); await this.tasks.save(task); } return task; }
  async list(q: any, user: any) { const qb = this.tasks.createQueryBuilder('task').where('1=1'); if (user.role !== Role.ADMIN) qb.andWhere('task.project_id IN (SELECT project_id FROM project_members WHERE user_id = :uid)', { uid: user.id }); if (q.status) qb.andWhere('task.status = :status', { status: q.status }); if (q.priority) qb.andWhere('task.priority = :priority', { priority: q.priority }); if (q.projectId) qb.andWhere('task.project_id = :projectId', { projectId: q.projectId }); if (q.assigneeId) qb.andWhere('task.assignee_id = :assigneeId', { assigneeId: q.assigneeId }); if (q.dueBefore) qb.andWhere('task.due_date <= :dueBefore', { dueBefore: q.dueBefore }); if (q.dueAfter) qb.andWhere('task.due_date >= :dueAfter', { dueAfter: q.dueAfter }); if (q.search) qb.andWhere(`to_tsvector('english', coalesce(task.title,'') || ' ' || coalesce(task.description,'')) @@ websearch_to_tsquery('english', :search)`, { search: q.search }); const sort = ({ createdAt: 'task.created_at', dueDate: 'task.due_date', priority: 'task.priority' } as any)[q.sortBy ?? 'createdAt']; qb.orderBy(sort, q.order ?? 'DESC').skip(((q.page ?? 1) - 1) * (q.limit ?? 20)).take(q.limit ?? 20); const [data, total] = await qb.getManyAndCount(); return { data, meta: { total, page: q.page ?? 1, limit: q.limit ?? 20, totalPages: Math.ceil(total / (q.limit ?? 20)) } }; }
  async get(id: string, user: any) { const task = await this.tasks.findOne({ where: { id } }); if (!task) throw new NotFoundException('Task not found'); await this.projects.assertMember(task.projectId, user); const [approvals, activity] = await Promise.all([this.approvals.find({ where: { taskId: id }, order: { stepOrder: 'ASC' } }), this.logs.find({ where: { taskId: id }, order: { createdAt: 'ASC' } })]); return { ...task, approvals, activity }; }
  async update(id: string, dto: any, user: any) { const task = await this.tasks.findOne({ where: { id } }); if (!task) throw new NotFoundException('Task not found'); await this.projects.assertMember(task.projectId, user); const before = { ...task }; Object.assign(task, dto); const saved = await this.tasks.save(task); for (const key of Object.keys(dto)) if ((before as any)[key] !== (dto as any)[key]) await this.logs.save(this.logs.create({ taskId: id, userId: user.id, action: `task.${key}_changed`, oldValue: String((before as any)[key] ?? ''), newValue: String((dto as any)[key] ?? '') })); if (saved.status === TaskStatus.DONE && saved.escalationWorkflowId) await this.temporal.cancelDeadline(saved.escalationWorkflowId); return saved; }
  async remove(id: string, user: any) { const task = await this.tasks.findOne({ where: { id } }); if (!task) throw new NotFoundException('Task not found'); await this.projects.assertMember(task.projectId, user); await this.tasks.softRemove(task); }
  async assign(id: string, assigneeId: string | null, user: any) { const task = await this.tasks.findOne({ where: { id } }); if (!task) throw new NotFoundException('Task not found'); if (assigneeId) await this.assertProjectMember(task.projectId, assigneeId); return this.update(id, { assigneeId }, user); }
  async submitApproval(id: string, approverIds: string[], user: any) { if (!approverIds.length) throw new BadRequestException('At least one approver is required'); const task = await this.tasks.findOne({ where: { id } }); if (!task) throw new NotFoundException('Task not found'); await this.projects.assertMember(task.projectId, user); for (const approverId of approverIds) await this.assertProjectMember(task.projectId, approverId); await this.approvals.save(approverIds.map((approverId, stepOrder) => this.approvals.create({ taskId: id, approverId, stepOrder, status: ApprovalStatus.PENDING }))); const workflowId = await this.temporal.startApproval(id, approverIds); task.approvalWorkflowId = workflowId; task.status = TaskStatus.IN_REVIEW; await this.tasks.save(task); return { workflowId }; }
  async approvalDecision(taskId: string, approvalId: string, decision: ApprovalStatus, comment: string | undefined, user: any) { const approval = await this.approvals.findOne({ where: { id: approvalId, taskId } }); if (!approval) throw new NotFoundException('Approval not found'); if (approval.approverId !== user.id && user.role !== Role.ADMIN) throw new ForbiddenException('Only the assigned approver can decide this approval'); if (approval.status !== ApprovalStatus.PENDING) throw new BadRequestException('Approval is already decided'); approval.status = decision; approval.comment = comment ?? null; approval.decidedAt = new Date(); await this.approvals.save(approval); const task = await this.tasks.findOne({ where: { id: taskId } }); if (task?.approvalWorkflowId) await this.temporal.signalApproval(task.approvalWorkflowId, decision, comment); return approval; }
  async workflowStatus(id: string, user: any) { const task = await this.tasks.findOne({ where: { id } }); if (!task) throw new NotFoundException('Task not found'); await this.projects.assertMember(task.projectId, user); if (!task.approvalWorkflowId) return { status: 'NOT_STARTED' }; return this.temporal.queryApproval(task.approvalWorkflowId); }
  private async assertProjectMember(projectId: string, userId: string) { const user = await this.users.findById(userId); if (!user) throw new NotFoundException('User not found'); const member = await this.members.findOne({ where: { projectId, userId } }); if (!member) throw new ForbiddenException('User must be a member of the project'); }
}
