export enum Role { ADMIN = 'ADMIN', PROJECT_MANAGER = 'PROJECT_MANAGER', DEVELOPER = 'DEVELOPER', VIEWER = 'VIEWER' }
export enum ProjectRole { OWNER = 'OWNER', MANAGER = 'MANAGER', CONTRIBUTOR = 'CONTRIBUTOR', VIEWER = 'VIEWER' }
